"""Register and export the complete SQLAlchemy ORM metadata graph."""

from infrastructure.persistence.metadata import Base
from infrastructure.persistence.orm.activity_annotation import (
    ActivityAnnotationRow,
    TransactionDecisionLinkRow,
)
from infrastructure.persistence.orm.agent import (
    AgentChannelBindingRow,
    AgentChannelCursorRow,
    AgentChannelHandoffRow,
    AgentConversationRow,
    AgentMessageRow,
    AgentPendingActionRow,
    AgentToolReceiptRow,
    AgentTurnRow,
)
from infrastructure.persistence.orm.agent_preferences import (
    AgentPreferencesRevisionRow,
    AgentPreferencesRow,
)
from infrastructure.persistence.orm.catalyst_agenda import (
    CatalystAgendaIdentityRow,
    CatalystAgendaSyncReceiptRow,
    CatalystAgendaVersionRow,
)
from infrastructure.persistence.orm.challenge_workflow import (
    ChallengeFindingRow,
    ChallengeQuestionRow,
    ChallengeReviewResolutionRow,
    ChallengeReviewRow,
    WorkflowRunFactArtifactRow,
    WorkflowRunRow,
    WorkflowRunStepRow,
)
from infrastructure.persistence.orm.common import JsonStringTuple
from infrastructure.persistence.orm.futures import (
    ContinuousContractMappingRow,
    ContinuousSeriesDefinitionRow,
    FuturesContractRow,
    FuturesContractStatisticsRow,
    FuturesContractVersionRow,
    FuturesProductRow,
    FuturesProductVersionRow,
)
from infrastructure.persistence.orm.judgment_scorecard import JudgmentScorecardRunRow
from infrastructure.persistence.orm.monitoring import (
    MonitorEventResolutionRow,
    MonitorEventRow,
    MonitorIdentityRow,
    MonitorJudgmentRow,
    MonitorRuleStateRow,
    MonitorRunObservationRow,
    MonitorRunRow,
    MonitorVersionRow,
    NotificationOutboxRow,
)
from infrastructure.persistence.orm.operations import (
    BehaviorActionObservationRow,
    BehaviorReviewRunRow,
    BrokerOrderIntentRow,
    DailyEquitySnapshotRow,
    ExternalNoteIdentityRow,
    ExternalNoteInterpretationRow,
    ExternalNoteReviewRevisionRow,
    ExternalNoteRevisionRow,
    ExternalNoteSyncReceiptRow,
    IndustryMetricObservationRow,
    JournalActivationRow,
    OperationalJobRunRow,
    PostMarketSyncRunRow,
    TradeCycleOverrideRevisionRow,
)
from infrastructure.persistence.orm.portfolio_risk import (
    AccountPositionRow,
    AccountSnapshotRow,
    PortfolioSnapshotRow,
    RiskPolicyRow,
    SubjectPositionLinkRow,
    TradePlanConditionRow,
    TradePlanIdentityRow,
    TradePlanVersionRow,
)
from infrastructure.persistence.orm.provider_state import (
    InstrumentAliasRow,
    InstrumentRow,
    ProviderCacheRow,
    ProviderHealthRow,
    ProviderRateLimitRow,
    ProviderRouteReceiptRow,
    RedditCooldownRow,
    RedditSampleCacheRow,
)
from infrastructure.persistence.orm.research import (
    AssumptionRow,
    CandidateThesisRevisionRow,
    InvalidationConditionRow,
    OpenQuestionRow,
    ResearchSubjectRow,
    ThesisRevisionRow,
    ThesisRow,
    WatchlistGroupRow,
    WatchlistMembershipRow,
    WatchlistMutationRow,
)
from infrastructure.persistence.orm.research_memory import (
    DecisionRecordRow,
    EvidenceAssessmentRow,
    JournalEntryRow,
    ResearchEventRow,
    ResearchEvidenceRow,
    ResearchReportRow,
    SubjectEvidenceLinkRow,
)
from infrastructure.persistence.orm.research_selection import WatchlistItemRow
from infrastructure.persistence.orm.review_item import (
    ReviewItemActionRow,
    ReviewItemOccurrenceRow,
    ReviewItemRow,
)
from infrastructure.persistence.orm.system import (
    SchemaVersionRow,
    SystemAuditLogRow,
)
from infrastructure.persistence.orm.trade_retro import (
    TradeRetroExportReceiptRow,
    TradeRetroPlanSnapshotRow,
    TradeRetroReviewRevisionRow,
    TradeRetroRunRow,
)
from infrastructure.persistence.orm.transactions import (
    AccountActivityCoverageReceiptRow,
    AccountTransactionRow,
)

__all__ = [
    "Base",
    "ExternalNoteIdentityRow",
    "ExternalNoteInterpretationRow",
    "ExternalNoteReviewRevisionRow",
    "ExternalNoteRevisionRow",
    "ExternalNoteSyncReceiptRow",
    "BehaviorActionObservationRow",
    "BehaviorReviewRunRow",
    "AgentConversationRow",
    "AgentChannelBindingRow",
    "AgentMessageRow",
    "AgentToolReceiptRow",
    "AgentPendingActionRow",
    "AgentTurnRow",
    "AgentChannelCursorRow",
    "AgentChannelHandoffRow",
    "AgentPreferencesRow",
    "AgentPreferencesRevisionRow",
    "BrokerOrderIntentRow",
    "DailyEquitySnapshotRow",
    "JsonStringTuple",
    "SchemaVersionRow",
    "SystemAuditLogRow",
    "ResearchSubjectRow",
    "ThesisRow",
    "ThesisRevisionRow",
    "AssumptionRow",
    "InvalidationConditionRow",
    "OpenQuestionRow",
    "WatchlistItemRow",
    "WatchlistGroupRow",
    "WatchlistMembershipRow",
    "WatchlistMutationRow",
    "CandidateThesisRevisionRow",
    "InstrumentRow",
    "InstrumentAliasRow",
    "ProviderCacheRow",
    "ProviderHealthRow",
    "ProviderRouteReceiptRow",
    "ProviderRateLimitRow",
    "RedditSampleCacheRow",
    "RedditCooldownRow",
    "ResearchEvidenceRow",
    "SubjectEvidenceLinkRow",
    "EvidenceAssessmentRow",
    "ResearchReportRow",
    "ResearchEventRow",
    "DecisionRecordRow",
    "JournalEntryRow",
    "JournalActivationRow",
    "AccountSnapshotRow",
    "AccountPositionRow",
    "PortfolioSnapshotRow",
    "SubjectPositionLinkRow",
    "RiskPolicyRow",
    "TradePlanIdentityRow",
    "TradePlanVersionRow",
    "TradePlanConditionRow",
    "MonitorIdentityRow",
    "MonitorJudgmentRow",
    "MonitorVersionRow",
    "MonitorRuleStateRow",
    "MonitorEventRow",
    "MonitorEventResolutionRow",
    "MonitorRunRow",
    "MonitorRunObservationRow",
    "NotificationOutboxRow",
    "ChallengeReviewRow",
    "ChallengeReviewResolutionRow",
    "ChallengeQuestionRow",
    "ChallengeFindingRow",
    "WorkflowRunRow",
    "WorkflowRunStepRow",
    "WorkflowRunFactArtifactRow",
    "AccountActivityCoverageReceiptRow",
    "AccountTransactionRow",
    "ActivityAnnotationRow",
    "TransactionDecisionLinkRow",
    "FuturesProductRow",
    "FuturesProductVersionRow",
    "FuturesContractRow",
    "FuturesContractVersionRow",
    "FuturesContractStatisticsRow",
    "ContinuousSeriesDefinitionRow",
    "ContinuousContractMappingRow",
    "IndustryMetricObservationRow",
    "OperationalJobRunRow",
    "PostMarketSyncRunRow",
    "TradeRetroPlanSnapshotRow",
    "TradeRetroReviewRevisionRow",
    "TradeRetroRunRow",
    "TradeRetroExportReceiptRow",
    "TradeCycleOverrideRevisionRow",
    "JudgmentScorecardRunRow",
    "ReviewItemRow",
    "ReviewItemActionRow",
    "ReviewItemOccurrenceRow",
    "CatalystAgendaIdentityRow",
    "CatalystAgendaSyncReceiptRow",
    "CatalystAgendaVersionRow",
    "CatalystAgendaSyncReceiptRow",
]
