"""Register and export the complete SQLAlchemy ORM metadata graph."""

from infrastructure.persistence.metadata import Base
from infrastructure.persistence.orm.challenge_workflow import (
    ChallengeFindingRow,
    ChallengeQuestionRow,
    ChallengeReviewResolutionRow,
    ChallengeReviewRow,
    WorkflowRunFactArtifactRow,
    WorkflowRunRow,
    WorkflowRunStepRow,
)
from infrastructure.persistence.orm.common import JsonStringTuple
from infrastructure.persistence.orm.futures import (
    ContinuousContractMappingRow,
    ContinuousSeriesDefinitionRow,
    FuturesContractRow,
    FuturesContractStatisticsRow,
    FuturesContractVersionRow,
    FuturesProductRow,
    FuturesProductVersionRow,
)
from infrastructure.persistence.orm.monitoring import (
    MonitorEventResolutionRow,
    MonitorEventRow,
    MonitorIdentityRow,
    MonitorJudgmentRow,
    MonitorRuleStateRow,
    MonitorRunObservationRow,
    MonitorRunRow,
    MonitorVersionRow,
    NotificationOutboxRow,
)
from infrastructure.persistence.orm.operations import (
    IndustryMetricObservationRow,
    PostMarketSyncRunRow,
)
from infrastructure.persistence.orm.portfolio_risk import (
    AccountPositionRow,
    AccountSnapshotRow,
    PortfolioSnapshotRow,
    RiskPolicyRow,
    SubjectPositionLinkRow,
    TradePlanConditionRow,
    TradePlanIdentityRow,
    TradePlanVersionRow,
)
from infrastructure.persistence.orm.provider_state import (
    InstrumentAliasRow,
    InstrumentRow,
    ProviderCacheRow,
    ProviderHealthRow,
    ProviderRateLimitRow,
    ProviderRouteReceiptRow,
    RedditCooldownRow,
    RedditSampleCacheRow,
)
from infrastructure.persistence.orm.research import (
    AssumptionRow,
    CandidateThesisRevisionRow,
    InvalidationConditionRow,
    OpenQuestionRow,
    ResearchSubjectRow,
    ThesisRevisionRow,
    ThesisRow,
    WatchlistGroupRow,
    WatchlistMembershipRow,
    WatchlistMutationRow,
)
from infrastructure.persistence.orm.research_memory import (
    DecisionRecordRow,
    EvidenceAssessmentRow,
    JournalEntryRow,
    ResearchEventRow,
    ResearchEvidenceRow,
    ResearchReportRow,
    SubjectEvidenceLinkRow,
)
from infrastructure.persistence.orm.research_selection import WatchlistItemRow
from infrastructure.persistence.orm.system import (
    SchemaVersionRow,
    SystemAuditLogRow,
)
from infrastructure.persistence.orm.transactions import (
    AccountActivityCoverageReceiptRow,
    AccountTransactionRow,
)

__all__ = [
    "Base",
    "JsonStringTuple",
    "SchemaVersionRow",
    "SystemAuditLogRow",
    "ResearchSubjectRow",
    "ThesisRow",
    "ThesisRevisionRow",
    "AssumptionRow",
    "InvalidationConditionRow",
    "OpenQuestionRow",
    "WatchlistItemRow",
    "WatchlistGroupRow",
    "WatchlistMembershipRow",
    "WatchlistMutationRow",
    "CandidateThesisRevisionRow",
    "InstrumentRow",
    "InstrumentAliasRow",
    "ProviderCacheRow",
    "ProviderHealthRow",
    "ProviderRouteReceiptRow",
    "ProviderRateLimitRow",
    "RedditSampleCacheRow",
    "RedditCooldownRow",
    "ResearchEvidenceRow",
    "SubjectEvidenceLinkRow",
    "EvidenceAssessmentRow",
    "ResearchReportRow",
    "ResearchEventRow",
    "DecisionRecordRow",
    "JournalEntryRow",
    "AccountSnapshotRow",
    "AccountPositionRow",
    "PortfolioSnapshotRow",
    "SubjectPositionLinkRow",
    "RiskPolicyRow",
    "TradePlanIdentityRow",
    "TradePlanVersionRow",
    "TradePlanConditionRow",
    "MonitorIdentityRow",
    "MonitorJudgmentRow",
    "MonitorVersionRow",
    "MonitorRuleStateRow",
    "MonitorEventRow",
    "MonitorEventResolutionRow",
    "MonitorRunRow",
    "MonitorRunObservationRow",
    "NotificationOutboxRow",
    "ChallengeReviewRow",
    "ChallengeReviewResolutionRow",
    "ChallengeQuestionRow",
    "ChallengeFindingRow",
    "WorkflowRunRow",
    "WorkflowRunStepRow",
    "WorkflowRunFactArtifactRow",
    "AccountActivityCoverageReceiptRow",
    "AccountTransactionRow",
    "FuturesProductRow",
    "FuturesProductVersionRow",
    "FuturesContractRow",
    "FuturesContractVersionRow",
    "FuturesContractStatisticsRow",
    "ContinuousSeriesDefinitionRow",
    "ContinuousContractMappingRow",
    "IndustryMetricObservationRow",
    "PostMarketSyncRunRow",
]
