"""Cross-asset futures, spot, and basis domain (Phase 3A)."""

from domain.cross_asset.basis_service import (
    BASIS_FORMULA_VERSION,
    build_basis_snapshot,
    classify_curve_shape,
)
from domain.cross_asset.cme_identity import (
    CME_METAL_ROOTS,
    CmeContinuousCode,
    CmeContractCode,
    build_cme_continuous_symbol,
    is_legacy_us_continuous_proxy,
    parse_cme_continuous_code,
    parse_cme_contract_code,
    yahoo_symbol_for_cme_instrument,
)
from domain.cross_asset.dce_identity import (
    DCE_LH_CONTRACT_MONTHS,
    DCE_LH_PRODUCT_KEY,
    DCE_LH_ROOT,
    DceLhContractCode,
    parse_dce_lh_contract_code,
    parse_dce_lh_instrument_id,
)
from domain.cross_asset.enums import (
    BasisComparability,
    ContinuousAdjustment,
    ContractLifecycleStatus,
    CurveCompleteness,
    CurveShape,
    OfferSide,
    PriceBasis,
    RollRule,
    SettlementMethod,
    SettlementStatus,
    SpotVenueBasis,
    SpotVolumeBasis,
)
from domain.cross_asset.futures_models import (
    ContinuousContractMapping,
    ContinuousSeriesDefinition,
    FuturesContractDefinition,
    FuturesContractStatistics,
    FuturesCurveContractPoint,
    FuturesCurveSnapshot,
    FuturesProductDefinition,
)
from domain.cross_asset.spot_models import CommoditySpotBarSeries, SpotObservation

__all__ = [
    "BASIS_FORMULA_VERSION",
    "CME_METAL_ROOTS",
    "DCE_LH_CONTRACT_MONTHS",
    "DCE_LH_PRODUCT_KEY",
    "DCE_LH_ROOT",
    "BasisComparability",
    "CmeContinuousCode",
    "CmeContractCode",
    "CommoditySpotBarSeries",
    "ContinuousAdjustment",
    "ContinuousContractMapping",
    "ContinuousSeriesDefinition",
    "ContractLifecycleStatus",
    "CurveCompleteness",
    "CurveShape",
    "DceLhContractCode",
    "FuturesContractDefinition",
    "FuturesContractStatistics",
    "FuturesCurveContractPoint",
    "FuturesCurveSnapshot",
    "FuturesProductDefinition",
    "OfferSide",
    "PriceBasis",
    "RollRule",
    "SettlementMethod",
    "SettlementStatus",
    "SpotObservation",
    "SpotVenueBasis",
    "SpotVolumeBasis",
    "build_basis_snapshot",
    "build_cme_continuous_symbol",
    "classify_curve_shape",
    "is_legacy_us_continuous_proxy",
    "parse_cme_continuous_code",
    "parse_cme_contract_code",
    "parse_dce_lh_contract_code",
    "parse_dce_lh_instrument_id",
    "yahoo_symbol_for_cme_instrument",
]
