"""Deterministic Thesis judgment scorecard domain records."""

from domain.scorecard.enums import ScorecardDimensionStatus, ScorecardStatus
from domain.scorecard.models import (
    JUDGMENT_SCORECARD_ALGORITHM_VERSION,
    JUDGMENT_SCORECARD_DIMENSION_CODES,
    JUDGMENT_SCORECARD_S0_ALGORITHM_VERSION,
    JUDGMENT_SCORECARD_S0_DIMENSION_CODES,
    JUDGMENT_SCORECARD_S0_SCHEMA_VERSION,
    JUDGMENT_SCORECARD_S1_ALGORITHM_VERSION,
    JUDGMENT_SCORECARD_S1_DIMENSION_CODES,
    JUDGMENT_SCORECARD_S1_SCHEMA_VERSION,
    JUDGMENT_SCORECARD_SCHEMA_VERSION,
    JudgmentScorecardRun,
    ScorecardDimension,
    ScorecardSourceRef,
)

__all__ = [
    "ScorecardDimensionStatus",
    "ScorecardStatus",
    "JUDGMENT_SCORECARD_ALGORITHM_VERSION",
    "JUDGMENT_SCORECARD_DIMENSION_CODES",
    "JUDGMENT_SCORECARD_S0_ALGORITHM_VERSION",
    "JUDGMENT_SCORECARD_S0_DIMENSION_CODES",
    "JUDGMENT_SCORECARD_S0_SCHEMA_VERSION",
    "JUDGMENT_SCORECARD_S1_ALGORITHM_VERSION",
    "JUDGMENT_SCORECARD_S1_DIMENSION_CODES",
    "JUDGMENT_SCORECARD_S1_SCHEMA_VERSION",
    "JUDGMENT_SCORECARD_SCHEMA_VERSION",
    "JudgmentScorecardRun",
    "ScorecardDimension",
    "ScorecardSourceRef",
]
