"""Stable public façade for closed A-share Pydantic DTOs.

Capability implementations live in focused sibling modules. Existing imports from
``application.dto.a_share`` remain compatible.
"""

from application.dto import a_share_core_outputs as _core
from application.dto import a_share_inputs as _inputs
from application.dto import a_share_market_outputs as _market
from application.dto import a_share_product_outputs as _product
from application.dto import a_share_signal_outputs as _signal

A_SHARE_DEFAULT_FINANCIAL_METRICS = _inputs.A_SHARE_DEFAULT_FINANCIAL_METRICS

AShareGetSnapshotInput = _inputs.AShareGetSnapshotInput
AShareGetFinancialStatementsInput = _inputs.AShareGetFinancialStatementsInput
AShareGetIndustryCycleInput = _inputs.AShareGetIndustryCycleInput
AShareGetCompanyOperatingMetricsInput = _inputs.AShareGetCompanyOperatingMetricsInput
AShareGetMarketStructureInput = _inputs.AShareGetMarketStructureInput
AShareGetCapitalSnapshotInput = _inputs.AShareGetCapitalSnapshotInput
AShareGetLimitUpContextInput = _inputs.AShareGetLimitUpContextInput
AShareGetSentimentSnapshotInput = _inputs.AShareGetSentimentSnapshotInput
AShareGetEtfOptionSnapshotInput = _inputs.AShareGetEtfOptionSnapshotInput
ResearchSearchReportsInput = _inputs.ResearchSearchReportsInput

AShareQuoteDTO = _core.AShareQuoteDTO
OrderBookLevelDTO = _core.OrderBookLevelDTO
TradeTickDTO = _core.TradeTickDTO
AShareBarDTO = _core.AShareBarDTO
FundamentalMetricDTO = _core.FundamentalMetricDTO
FinancialStatementLineDTO = _core.FinancialStatementLineDTO
AShareFinancialMetricDTO = _core.AShareFinancialMetricDTO
AShareFinancialPeriodDTO = _core.AShareFinancialPeriodDTO
AShareFinancialStatementsDTO = _core.AShareFinancialStatementsDTO
F10SectionDTO = _core.F10SectionDTO
ConsensusEstimateDTO = _core.ConsensusEstimateDTO
AnalystReportItemDTO = _core.AnalystReportItemDTO
AnnouncementItemDTO = _core.AnnouncementItemDTO
NewsItemDTO = _core.NewsItemDTO
InteractiveQAItemDTO = _core.InteractiveQAItemDTO

IndustryPerformanceRowDTO = _market.IndustryPerformanceRowDTO
MarketBoardSnapshotDTO = _market.MarketBoardSnapshotDTO
FundFlowPointDTO = _market.FundFlowPointDTO
NorthboundFlowPointDTO = _market.NorthboundFlowPointDTO
DragonTigerSeatDTO = _market.DragonTigerSeatDTO
DragonTigerRecordDTO = _market.DragonTigerRecordDTO
MarginRecordDTO = _market.MarginRecordDTO
BlockTradeRecordDTO = _market.BlockTradeRecordDTO
ShareholderCountRecordDTO = _market.ShareholderCountRecordDTO
ChipDistributionBinDTO = _market.ChipDistributionBinDTO
ChipDistributionSnapshotDTO = _market.ChipDistributionSnapshotDTO
UnlockRecordDTO = _market.UnlockRecordDTO
DividendRecordDTO = _market.DividendRecordDTO

LimitPoolEntryDTO = _signal.LimitPoolEntryDTO
LimitUpLadderRungDTO = _signal.LimitUpLadderRungDTO
LimitUpContextDTO = _signal.LimitUpContextDTO
SentimentSignalDTO = _signal.SentimentSignalDTO
EtfOptionContractDTO = _signal.EtfOptionContractDTO
EtfOptionQuoteDTO = _signal.EtfOptionQuoteDTO
OptionGreeksDTO = _signal.OptionGreeksDTO
EtfOptionSnapshotDTO = _signal.EtfOptionSnapshotDTO

AShareCompositeSnapshotDTO = _product.AShareCompositeSnapshotDTO
AShareMarketStructureSnapshotDTO = _product.AShareMarketStructureSnapshotDTO
AShareCapitalSnapshotDTO = _product.AShareCapitalSnapshotDTO
IndustryMetricObservationDTO = _product.IndustryMetricObservationDTO
IndustryMetricCoverageDTO = _product.IndustryMetricCoverageDTO
IndustryCycleSnapshotDTO = _product.IndustryCycleSnapshotDTO
AShareLimitUpContextProductDTO = _product.AShareLimitUpContextProductDTO
AShareSentimentSnapshotDTO = _product.AShareSentimentSnapshotDTO
ResearchReportSearchDTO = _product.ResearchReportSearchDTO
DocumentParseReceiptDTO = _product.DocumentParseReceiptDTO
CompanyOperatingMetricObservationDTO = _product.CompanyOperatingMetricObservationDTO
CompanyOperatingMetricsSnapshotDTO = _product.CompanyOperatingMetricsSnapshotDTO
