"""Initialize or upgrade an installed Trading Partner core runtime."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from alembic import command
from alembic.config import Config

from bootstrap import load_settings

_RUNTIME_ENV_NAME = "runtime.env"
_DATABASE_NAME = "trading_partner.db"


def default_runtime_home() -> Path:
    """Return a stable per-user application-data directory without creating it."""
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Application Support" / "trading-partner"
    if os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        return base / "trading-partner"
    base = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
    return base / "trading-partner"


def migration_script_location() -> Path:
    """Resolve migrations from a source checkout or the installed wheel."""
    source = Path(__file__).resolve().parents[3] / "migrations"
    if (source / "env.py").is_file():
        return source.resolve()
    installed = Path(__file__).resolve().parents[2] / "trading_partner_migrations"
    if (installed / "env.py").is_file():
        return installed.resolve()
    raise RuntimeError("packaged Alembic migrations are unavailable")


def _sqlite_url(database_path: Path) -> str:
    return f"sqlite:///{database_path.resolve()}"


def _initial_env(database_path: Path) -> str:
    runtime_root = database_path.parent.resolve()
    return "\n".join(
        (
            "# Generated by trading-partner-init. Add optional Provider keys below.",
            "APP_NAME=trading-partner",
            "APP_ENV=development",
            "LOG_LEVEL=INFO",
            f"DATABASE_URL={_sqlite_url(database_path)}",
            "MCP_SERVER_NAME=trading-partner",
            "DEFAULT_TIMEZONE=UTC",
            "PROVIDER_TIMEOUT_SECONDS=30.0",
            f"RUNTIME_ROOT={runtime_root}",
            "",
        )
    )


def _write_new_env(path: Path, *, database_path: Path) -> None:
    path.write_text(_initial_env(database_path), encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def _upgrade_database(database_url: str) -> None:
    config = Config()
    config.set_main_option("script_location", str(migration_script_location()))
    config.attributes["database_url"] = database_url
    command.upgrade(config, "head")


def _mcp_executable() -> str:
    invoked = Path(sys.argv[0]).expanduser()
    if invoked.name in {"trading-partner-init", "trading-partner-init.exe"}:
        suffix = ".exe" if invoked.suffix == ".exe" else ""
        sibling = invoked.resolve().with_name(f"trading-partner-mcp{suffix}")
        if sibling.is_file():
            return str(sibling)
    executable = shutil.which("trading-partner-mcp")
    return str(Path(executable).resolve()) if executable else "trading-partner-mcp"


def initialize(runtime_home: Path) -> dict[str, Any]:
    """Create one explicit runtime config and idempotently upgrade its database."""
    home = runtime_home.expanduser().resolve()
    home.mkdir(parents=True, exist_ok=True)
    home.chmod(stat.S_IRWXU)
    env_file = home / _RUNTIME_ENV_NAME
    database_path = home / _DATABASE_NAME
    created = not env_file.exists()
    if created:
        _write_new_env(env_file, database_path=database_path)
    elif not env_file.is_file() or env_file.is_symlink():
        raise RuntimeError("runtime environment path must be an existing regular file")

    settings = load_settings(env_file)
    _upgrade_database(settings.database_url)
    return {
        "ok": True,
        "created": created,
        "runtime_home": str(home),
        "env_file": str(env_file),
        "database_url": settings.redacted_dict()["database_url"],
        "mcp_command": _mcp_executable(),
        "mcp_args": ["--env-file", str(env_file)],
        "next_action": "ADD_MCP_HOST_CONFIG_AND_CALL_SYSTEM_HEALTH",
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="trading-partner-init",
        description=(
            "Create an owner-only core runtime config and idempotently upgrade its database."
        ),
    )
    parser.add_argument(
        "--runtime-home",
        type=Path,
        default=default_runtime_home(),
        help="Application-data directory; existing runtime.env is preserved.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit the secret-safe MCP command receipt as JSON.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> None:
    args = _parser().parse_args(argv)
    receipt = initialize(args.runtime_home)
    if args.json:
        print(json.dumps(receipt, ensure_ascii=False, sort_keys=True))
        return
    print(f"Trading Partner runtime ready: {receipt['runtime_home']}")
    print(f"MCP command: {receipt['mcp_command']}")
    print(f"MCP args: {' '.join(receipt['mcp_args'])}")
    print("Next: add that command to your MCP host and call system_health.")


if __name__ == "__main__":
    main()
